name: mineral-hybrid
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip=24.*
  - numpy=1.26.*
  - pandas=2.2.*
  - scipy=1.11.*
  - scikit-learn=1.4.*
  - matplotlib=3.8.*
  - pyyaml=6.0.*
  - pytorch=2.2.*
  - cpuonly
  - pip:
      - tensorflow==2.15.*
      - qiskit==1.0.*
      - qiskit-machine-learning==0.7.*
      - qiskit-aer==0.14.*
      - nbformat==5.10.*
      - tqdm==4.66.*
